#import "./../Fragments/Cart.gql"

mutation APPLY_COUPON($clientMutationId: String, $code: String!) {
  applyCoupon(
    input: { clientMutationId: $clientMutationId, code: $code }
  ) {
    cart {
      ...cart
    }
  }
}
