#import "./../Fragments/Cart.gql"

mutation REMOVE_COUPONS($clientMutationId: String, $codes: [String]) {
  removeCoupons(
    input: { clientMutationId: $clientMutationId, codes: $codes }
  ) {
    cart {
      ...cart
    }
  }
}
