#import "./../Fragments/SeoTaxonomy.gql"

query ProductCategory($slug: ID!) {
  productCategory(id: $slug, idType: SLUG) {
    id
    databaseId
    name
    description
    seo {
      ...seoTaxonomy
    }
  }
}
