#import "./../Products/Fragments/ProductDetails.gql"

query ProductCategory($slug: ID!) {
  productCategory(id: $slug, idType: SLUG) {
    id
    databaseId
    name
    description
    products {
      edges {
        node {
          ...productDetails
          slug
        }
      }
    }
  }
}
