#import "./../Products/Fragments/ProductDetails.gql"
#import "./../Fragments/SeoTaxonomy.gql"

query ProductCategory($slug: ID!) {
  productCategory(id: $slug, idType: SLUG) {
    id
    databaseId
    name
    description
    products(
      where: {
        orderby: { field: MENU_ORDER, order: ASC }
        stockStatus: IN_STOCK
      }
      first: 99
    ) {
      edges {
        node {
          ...productDetails
          slug
        }
      }
    }
    seo {
      ...seoTaxonomy
    }
  }
}
