fragment customer on Customer {
  id
  username
  firstName
  lastName
  email
  billing {
    address1
    address2
    city
    company
    country
    email
    firstName
    lastName
    phone
    postcode
    state
  }
}
