#import "./Fragments/PageContent.gql"

query Page($uri: ID!) {
  page(id: $uri, idType: URI) {
    ...pageContent
    databaseId
    content
    parent {
      ... on Page {
        databaseId
      }
    }
  }
}
