#import "./Fragments/PageContent.gql"

query Page($uri: ID!) {
  page(id: $uri, idType: URI) {
    ...pageContent
    databaseId
    content
    childPages {
      edges {
        node {
          id
        }
      }
    }
    parent {
      __typename
      ... on Page {
        databaseId
      }
    }
  }
}
