fragment Source on Source {
  id
  databaseId
  title: name
  taxonomy {
    node {
      name
    }
  }
}

fragment Subject on Subject {
  id
  databaseId
  title: name
  taxonomy {
    node {
      name
    }
  }
}

fragment SourceNode on PosterToSourceConnectionEdge {
  node {
    ...Source
  }
}

fragment Sources on PosterToSourceConnection {
  edges {
    ...SourceNode
  }
}

fragment SubjectNode on PosterToSubjectConnectionEdge {
  node {
    ...Subject
  }
}

fragment Subjects on PosterToSubjectConnection {
  edges {
    ...SubjectNode
  }
}

query GetTaxonomies {
  sources(first: 100) {
    edges {
      node {
        ...Source
      }
    }
  }
  subjects(first: 100) {
    edges {
      node {
        ...Subject
      }
    }
  }
}
