sudo: false
language: node_js
git:
  lfs_skip_smudge: true
node_js:
  - '10.0'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
after_success:
  - npm run lh -- https://loesje.michielkoning.nl/
  - npm run coveralls
