#import "./Fragments/RelatedPosters.gql"
#import "./Fragments/Post.gql"
#import "./../Fragments/Seo.gql"

query Post($uri: ID!) {
  post(id: $uri, idType: URI) {
    ...post
    content
    relatedPosters: relatedPostersGroup {
      ...relatedPostersPostGroup
    }
    # relatedProducts: relatedProductsGroup {
    #   ...relatedProductsPostGroup
    # }
    seo {
      ...seo
    }
  }
}
