#import "./Fragments/PostDetails.gql"

query Posts($first: Int, $after: String, $notIn: ID) {
  posts(first: $first, after: $after, where: { notIn: [$notIn] }) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        ...postDetails
        excerpt
        uri
      }
    }
  }
}
