#import "./Fragments/Post.gql"

query Posts($first: Int, $after: String, $where: RootQueryToPostConnectionWhereArgs) {
  posts(first: $first, after: $after, where: $where) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        ...post
        excerpt
        uri
      }
    }
  }
}
