#import "./Fragments/RelatedPosters.gql"
#import "./Fragments/Post.gql"
#import "./Fragments/RelatedProducts.gql"

query Post($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    ...post
    content
    relatedPosters: relatedPostersGroup {
      ...relatedPostersPostGroup
    }
    relatedProducts: relatedProductsGroup {
      ...relatedProductsPostGroup
    }
    # seo {
    #   ...seo
    # }
  }
}
