#import "./Fragments/RelatedPosters.gql"
#import "./Fragments/PostDetails.gql"
#import "./Fragments/RelatedProducts.gql"
#import "./../Fragments/Seo.gql"

query Post($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    ...postDetails
    content
    relatedPosters: relatedPostersGroup {
      ...relatedPostersPostGroup
    }
    relatedProducts: relatedProductsGroup {
      ...relatedProductsPostGroup
    }
    seo {
      ...seo
    }
  }
}
