fragment productDetails on Product {
  id
  databaseId
  name
  image {
    id
    altText
    medium: sourceUrl(size: MEDIUM)
    mediumLarge: sourceUrl(size: MEDIUM_LARGE)
  }
  ... on SimpleProduct {
    id
    regularPrice
    price
    salePrice
  }
  ... on VariableProduct {
    id
    regularPrice
    price
    salePrice
  }
}
