#import "./Page.gql"
#import "./RelatedPosters.gql"
#import "./RelatedProducts.gql"

fragment pageContent on Page {
  ...page
  content
  relatedPosters: relatedPostersGroup {
    ...relatedPostersPageGroup
  }
  relatedProducts: relatedProductsGroup {
    ...relatedProductsPageGroup
  }
  # seo {
  #   ...seo
  # }
}
