#import "./Page.gql"
#import "./RelatedPosters.gql"
#import "./RelatedProducts.gql"
#import "./../../Fragments/Seo.gql"

fragment pageContent on Page {
  ...page
  content
  relatedPosters: relatedPostersGroup {
    ...relatedPostersGroup
  }
  relatedProducts: relatedProductsGroup {
    ...relatedProductsGroup
  }
  seo {
    ...seo
  }
}
