fragment relatedProductsPageGroup on Page_Relatedproductsgroup {
  title: relatedProductsTitle
  relatedProductsProducts {
    ... on Page_Relatedproductsgroup_relatedProductsProducts {
      product {
        ... on Product {
          productId
        }
      }
    }
  }
}
