fragment relatedPostersPageGroup on Page_Relatedpostersgroup {
  title: relatedPostersTitle
  search: relatedPostersSearch
  subjects: relatedPostersSubjects {
    ... on Subject {
      databaseId
      name
    }
  }
  posters: relatedPostersPosters {
    ... on Page_Relatedpostersgroup_relatedPostersPosters {
      poster {
        ... on Poster {
          databaseId
        }
      }
    }
  }
}
