fragment relatedProductsPageGroup on Page_Relatedproductsgroup {
  title: relatedProductsTitle
  relatedProductsProducts {
    product {
      ... on SimpleProduct {
        databaseId
      }
    }
  }
}
