fragment customer on Customer {
  id
  username
  billing {
    address1
    address2
    city
    company
    country
    email
    firstName
    lastName
    phone
    postcode
    state
  }
  shipping {
    address1
    address2
    city
    company
    country
    email
    firstName
    lastName
    phone
    postcode
    state
  }
}
