fragment relatedProductsPosterGroup on Poster_Relatedproductsgroup {
  title: relatedProductsTitle
  relatedProductsProducts {
    ... on Poster_Relatedproductsgroup_relatedProductsProducts {
      product {
        ... on Product {
          databaseId
        }
      }
    }
  }
}
