fragment relatedPostersGroup on Post_Relatedpostersgroup {
  title: relatedPostersTitle
  search: relatedPostersSearch
  subjects: relatedPostersSubjects {
    ... on Subject {
      databaseId
      name
    }
  }
  posters: relatedPostersPosters {
    ... on Post_Relatedpostersgroup_relatedPostersPosters {
      poster {
        ... on Post_Relatedpostersgroup_relatedPostersPosters_Poster {
          ... on Poster {
            databaseId
          }
        }
      }
    }
  }
}
