fragment relatedProductsPostGroup on Post_Relatedproductsgroup {
  title: relatedProductsTitle
  relatedProductsProducts {
    ... on Post_Relatedproductsgroup_relatedProductsProducts {
      product {
        ... on Product {
          productId
        }
      }
    }
  }
}
