fragment relatedProductsPostGroup on Post_Relatedproductsgroup {
  title: relatedProductsTitle
  products: relatedProductsProducts {
    ... on Post_Relatedproductsgroup_relatedProductsProducts {
      product {
        ... on Product {
          databaseId
        }
      }
    }
  }
}
