fragment menuItem on Page {
  id
  uri
  title
}

query Menu($aboutPageId: ID!, $joinPageId: ID!) {
  menu(id: "header-menu", idType: LOCATION) {
    id
    menuItems {
      edges {
        node {
          id
          uri
          title
        }
      }
    }
  }
}
