[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
