fragment seo2 on PostTypeSEO {
  canonical
  cornerstone
  metaDesc
  opengraphAuthor
  opengraphDescription
  opengraphImage {
    archive: sourceUrl(size: MEDIUM)
  }
  opengraphModifiedTime
  opengraphPublishedTime
  opengraphPublisher
  opengraphTitle
  opengraphType
  opengraphUrl
  title
  twitterDescription
  twitterImage {
    archive: sourceUrl(size: MEDIUM)
  }
  twitterTitle
}
