fragment seo on SEO {
  focuskw
  metaDesc
  metaKeywords
  metaRobotsNofollow
  metaRobotsNoindex
  opengraphDescription
  opengraphImage {
    archive: sourceUrl(size: THUMBNAIL)
  }
  opengraphTitle
  title
  twitterDescription
  twitterImage {
    archive: sourceUrl(size: THUMBNAIL)
  }
  twitterTitle
}
