fragment seoTaxonomy on TaxonomySEO {
  canonical
  cornerstone
  metaDesc
  opengraphAuthor
  opengraphDescription
  opengraphImage {
    mediaItemUrl
  }
  opengraphModifiedTime
  opengraphPublishedTime
  opengraphPublisher
  opengraphTitle
  opengraphType
  opengraphUrl
  title
  twitterDescription
  twitterImage {
    mediaItemUrl
  }
  twitterTitle
}
