query GET_BLOG {
  blog: pageBy(pageId: 1383) {
    title
    uri
    featuredImage {
      altText
      heroLarge: sourceUrl(size: HERO_LARGE)
      heroMedium: sourceUrl(size: HERO_MEDIUM)
      heroSmall: sourceUrl(size: HERO_SMALL)
    }
  }
}
