query GET_CHILDPAGES_BY_URI($parent: String, $notIn: [ID]) {
  pages: pages(where:{
  	parent: $parent,
    notIn: $notIn
  }) {
    edges {
      node {
        pageId
        id
        title
        uri
        excerpt
      }
    }
  }
}
