query GET_PRODUCTS {
  products(where: {featured: true, stockStatus: IN_STOCK}, first: 5) {
    edges {
      node {
        id
        name
        slug
        image {
          id
          medium: sourceUrl(size: MEDIUM)
          mediumLarge: sourceUrl(size: MEDIUM_LARGE)
        }
        ... on SimpleProduct {
          id
          price
          salePrice
        }
        ... on VariableProduct {
          id
          price
          salePrice
        }
      }
    }
  }
}
