query GET_FRONT_PAGE {
  page: pageBy(pageId: 1379) {
    title
    content
    featuredImage {
      altText
      heroLarge: sourceUrl(size: HERO_LARGE)
      heroMedium: sourceUrl(size: HERO_MEDIUM)
      heroSmall: sourceUrl(size: HERO_SMALL)
    }
    usps {
      text
    }
    offers {
      text
    }
    services {
      link
      title
      usps {
        text
      }
    }
  }
}
