query GET_MENU_BY_LOCATION($location: MenuLocationEnum) {
  menu: menus(where: { location: $location }) {
    edges {
      node {
        menuItems {
          edges {
            node {
              label
              url
              relativeUrl
              target
              childItems {
                edges {
                  node {
                    label
                    relativeUrl
                    url
                    target
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
