fragment PageBase on Page {
  id
  databaseId
  title
}

fragment RelatedPage on Page {
  ...PageBase
  excerpt
  uri
}

fragment RelatedPageNode on PageToPageConnectionEdge {
  node {
    ...RelatedPage
  }
}

fragment RelatedPages on PageToPageConnection {
  edges {
    ...RelatedPageNode
  }
}

fragment PageRelatedProduct on Page_Relatedproductsgroup_relatedProductsProducts_Product {
  ...Product
}

fragment PageRelatedProductNode on Page_Relatedproductsgroup_relatedProductsProducts {
    ... on Page_Relatedproductsgroup_relatedProductsProducts {
    product {
      ...PageRelatedProduct
    }
  }
}

fragment PageRelatedProducts on Page_Relatedproductsgroup {
  title: relatedProductsTitle
  products: relatedProductsProducts {
    ...PageRelatedProductNode
  }
}

fragment PageDetails on Page {
  ...PageBase
  content
  featuredImage {
    ...FeaturedImage
  }  
  videoGroup {
    youtubeId
  }
  relatedPages {
    ...RelatedPages
  }
  relatedPostersGroup {
    title: relatedPostersTitle
  }
  relatedPosters(first: 7) {
    ...RelatedPosters
  }
  relatedProducts: relatedProductsGroup {
    ...PageRelatedProducts
  }
  seo {
    ...seo
  }
}

query GetPageByUri($uri: ID!) {
  page(id: $uri, idType: URI) {
    ...PageDetails
  }
}

query GetPageByID($id: ID!) {
  page(id: $id, idType: DATABASE_ID) {
    ...PageDetails
  }
}

query GetPageHome($id: ID!) {
  page(id: $id, idType: DATABASE_ID) {
    ...PageDetails
  }
  posts(first: 3, where: {
    hasPassword: false
  }) {
    ...PostListItems
  }
}