fragment PageBase on Page {
  id
  databaseId
  title
}

fragment RelatedPage on Page {
  ...PageBase
  excerpt
  uri
}

fragment RelatedPageNode on PageToPageConnectionEdge {
  node {
    ...RelatedPage
  }
}

fragment RelatedPages on PageToPageConnection {
  edges {
    ...RelatedPageNode
  }
}

fragment PageDetails on Page {
  ...PageBase
  content
  videoGroup {
    youtubeId
  }
  relatedPages {
    ...RelatedPages
  }
  relatedPostersGroup {
    title: relatedPostersTitle
  }
  relatedPosters(first: 7) {
    ...RelatedPosters
  }
}

query GetPageByUri($uri: ID!) {
  page(id: $uri, idType: URI) {
    ...PageDetails
  }
}

query GetPageByID($id: ID!) {
  page(id: $id, idType: DATABASE_ID) {
    ...PageDetails
  }
}

query GetPageHome($id: ID!) {
  page(id: $id, idType: DATABASE_ID) {
    ...PageDetails
  }
  posts(first: 3, where: {
    hasPassword: false
  }) {
    ...PostListItems
  }
}