#import "./Fragments/PageContent.gql"

query GET_PAGE_BY_URI($uri: String) {
  page: pageBy(uri: $uri) {
    ...pageContent
    pageId
    content
    childPages {
      edges {
        node {
          id
        }
      }
    }
    parent {
      __typename
      ... on Page {
        pageId
      }
    }
  }
}
