query GET_POSTERS(
  $first: Int
  $after: String
  $where: RootQueryToPosterConnectionWhereArgs
) {
  posters(first: $first, after: $after, where: $where) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        id
        databaseId
        title
        slug
        featuredImage {
          id
          medium: sourceUrl(size: MEDIUM)
        }
      }
    }
  }
}
