query GET_POSTS($first: Int, $after: String, $notIn: [ID]) {
  posts(first: $first, after: $after, where: { notIn: $notIn }) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        id
        postId
        title
        excerpt
        date
        slug
        link
      }
    }
  }
}
