fragment PostBase on Post {
  id
  databaseId
  date
  title
}

fragment PostListItem on Post {
  ...PostBase
  excerpt
  slug
}

fragment PostListItemNode on RootQueryToPostConnectionEdge {
  node {
    ...PostListItem
  }
}

fragment PostListItems on RootQueryToPostConnection {
  edges {
    ...PostListItemNode
  }
}

fragment PostRelatedProduct on Post_Relatedproductsgroup_relatedProductsProducts_Product {
  ...Product
}

fragment PostRelatedProductNode on Post_Relatedproductsgroup_relatedProductsProducts {
    ... on Post_Relatedproductsgroup_relatedProductsProducts {
    product {
      ...PostRelatedProduct
    }
  }
}

fragment PostRelatedProducts on Post_Relatedproductsgroup {
  title: relatedProductsTitle
  products: relatedProductsProducts {
    ...PostRelatedProductNode
  }
}

fragment PostDetails on Post {
  ...PostBase
  content
  videoGroup {
    youtubeId
  }
  featuredImage {
    ...FeaturedImage
  }
  relatedPostersGroup {
    title: relatedPostersTitle
  }
  relatedPosters(first: 7) {
    ...RelatedPosters
  }
  relatedProducts: relatedProductsGroup {
    ...PostRelatedProducts
  }    
  seo {
    ...seo
  }  
}

query GetPost($slug: ID!) {
  post(id: $slug, idType: URI) {
    ...PostDetails
  }
}

query GetPosts($after: String, $notIn: ID) {
  posts(first: 10, after: $after, where: {
    notIn: [$notIn],
    hasPassword: false
  }) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    ...PostListItems
  }
}