#import "./Fragments/Tags.gql"

query GET_POSTER($slug: String) {
  poster: posterBy(slug: $slug) {
    id
    posterId
    title
    date
    link
    slug
    featuredImage {
      id
      large: sourceUrl(size: LARGE)
      medium: sourceUrl(size: MEDIUM)
    }
    sources {
      edges {
        node {
          ...source
        }
      }
    }
    subjects {
      edges {
        node {
          ...subject
        }
      }
    }
  }
}
