#import "./Fragments/Seo.gql"

query GET_POST_BY_URI($uri: String) {
  post: postBy(uri: $uri) {
    postId
    content
    title
    date
    slug
    relatedPosters: relatedPostersGroup {
      title
      search
      subjects {
        ... on Subject {
          subjectId
          name
        }
      }
      posters {
        ... on Post_Relatedpostersgroup_posters {
          poster {
            ... on Post_Relatedpostersgroup_posters_Poster {
              ... on Poster {
                posterId
              }
            }
          }
        }
      }
    }
    seo {
      ...seo
    }
  }
}
