fragment PosterBase on Poster {
  id
  databaseId
  title
}

fragment Poster on Poster {
  ...PosterBase
  uri
  slug
  featuredImage {
    ...FeaturedImage
  }
}

fragment PosterNode on ContentNodeToPosterConnectionEdge {
  node {
    ...Poster
  }
}

fragment RelatedPosters on ContentNodeToPosterConnection {
  edges {
    ...PosterNode
  }
}
