query GET_POSTER($slug: String) {
  poster: posterBy(slug: $slug) {
    id
    posterId
    title
    date
    featuredImage {
      id
      large: sourceUrl(size: LARGE)
    }
    sources {
      edges {
        node {
          id
          name
        }
      }
    }
    subjects {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
