query GET_PRODUCT($slug: String) {
  product: productBy(slug: $slug) {
    id
    name
    slug
    shortDescription
    description
    price
    salePrice
    regularPrice
    image {
      id
      medium: sourceUrl(size: MEDIUM)
      mediumLarge: sourceUrl(size: MEDIUM_LARGE)
    }
    related {
      edges {
        node {
          id
          name
          slug
          price
          salePrice
        }
      }
    }
  }
}
