query GET_PRODUCT_CATEGORIES {
  productCategories(where: { hideEmpty: true, orderby: TERM_ORDER }) {
    edges {
      node {
        ...CategoryFields
        children {
          edges {
            node {
              ...CategoryFields
            }
          }
        }
      }
    }
  }
}

fragment CategoryFields on ProductCategory {
  id
  name
  uri
}
