#import "./Fragments/Product.gql"

query GET_PRODUCT($slug: String) {
  product(id: $slug, idType: SLUG) {
    ...product
    attributes {
      edges {
        node {
          id
          attributeId
          name
          options
          variation
          visible
        }
      }
    }
    related {
      edges {
        node {
          ...product
        }
      }
    }
  }
}
