query GET_PRODUCT_CATEGORIES {
  productCategories {
    edges {
      node {
        ...CategoryFields
        children {
          edges {
            node {
              ...CategoryFields
            }
          }
        }
      }
    }
  }
}

fragment CategoryFields on ProductCategory {
  id
  name
  slug
}
