query GET_SITEMAP {
  pages(first: 100) {
    edges {
      node {
        uri
        title
        uri
        content
        template
        featuredImage {
          altText
          heroLarge: sourceUrl(size: HERO_LARGE)
          heroMedium: sourceUrl(size: HERO_MEDIUM)
          heroSmall: sourceUrl(size: HERO_SMALL)
        }
        childPages {
          edges {
            node {
              uri
              title
              uri
              content
              template
              featuredImage {
                altText
                heroLarge: sourceUrl(size: HERO_LARGE)
                heroMedium: sourceUrl(size: HERO_MEDIUM)
                heroSmall: sourceUrl(size: HERO_SMALL)
              }
            }
          }
        }

      }
    }
  }
  posts(first:100) {
    edges {
      node {
        uri
      }
    }
  }
}
