query GET_TEACHERS_PAGE_BY_URI($uri: String) {
  page: pageBy(uri: $uri) {
    title
    content
    teachers {
      name
      bio
      socialMedia {
        facebook
        instagram
        linkedin
        twitter
      }
    }
    featuredImage {
      altText
      heroLarge: sourceUrl(size: HERO_LARGE)
      heroMedium: sourceUrl(size: HERO_MEDIUM)
      heroSmall: sourceUrl(size: HERO_SMALL)
    }
  }
}
