#import "./Fragments/ProductDetails.gql"

query Product($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    ...productDetails
    shortDescription
    description
    globalAttributes {
      nodes {
        id
        name
        slug
        variation
        position
        scope
        attributeId
        visible
        terms {
          nodes {
            id
            databaseId
            name
            slug
            count
          }
        }
      }
    }
    galleryImages {
      nodes {
        id
        altText
        thumbnail: sourceUrl(size: THUMBNAIL)
        medium: sourceUrl(size: MEDIUM)
        mediumLarge: sourceUrl(size: MEDIUM_LARGE)
      }
    }
    related {
      edges {
        node {
          databaseId
        }
      }
    }
    ... on SimpleProduct {
      stockStatus
    }
    ... on VariableProduct {
      stockStatus
    }
  }
}
