#import "./Fragments/ProductDetails.gql"

query Products($where: RootQueryToProductConnectionWhereArgs) {
  products(where: $where, first: 99) {
    edges {
      node {
        ...productDetails
        slug
      }
    }
  }
}
