#import "./Fragments/Product.gql"

query Product($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    ...product
    shortDescription
    description
    attributes {
      edges {
        node {
          id
          attributeId
          name
          options
          variation
          visible
        }
      }
    }
    galleryImages {
      nodes {
        id
        altText
        medium: sourceUrl(size: MEDIUM)
        mediumLarge: sourceUrl(size: MEDIUM_LARGE)
      }
    }
    related {
      edges {
        node {
          databaseId
        }
      }
    }
    ... on SimpleProduct {
      stockStatus
    }
  }
}
