query Products($where: RootQueryToProductConnectionWhereArgs, $first: Int) {
  products(where: $where, first: $first) {
    edges {
      node {
        slug
        id
        databaseId
        name
        featuredImage {
          id
          srcSet
          src: sourceUrl(size: LARGE)
          mediaDetails {
            width
            height
          }
        }
        ... on SimpleProduct {
          regularPrice
          price
          salePrice
        }
        ... on VariableProduct {
          regularPrice
          price
          salePrice
        }
      }
    }
  }
}
