#import "./Fragments/Poster.gql"
#import "./Fragments/Tags.gql"

query Poster($slug: ID!) {
  poster(id: $slug, idType: URI) {
    ...poster
    date
    link
    slug
    featuredImage {
      id
      large: sourceUrl(size: LARGE)
      medium: sourceUrl(size: MEDIUM)
    }
    sources {
      edges {
        node {
          ...source
        }
      }
    }
    subjects {
      edges {
        node {
          ...subject
        }
      }
    }
  }
}
