#import "./Fragments/PosterDetails.gql"
#import "./Fragments/SourceDetails.gql"
#import "./Fragments/SubjectDetails.gql"
#import "./Fragments/RelatedProducts.gql"
#import "./../Fragments/Seo.gql"

fragment relatedPosters on ContentNodeToPosterConnection {
  pageInfo {
    hasNextPage
    endCursor
  }
  edges {
    node {
      id
      databaseId
      title
      uri
      featuredImage {
        node {
          id
          medium: sourceUrl(size: MEDIUM)
        }
      }
    }
  }
}

query Poster($slug: ID!) {
  poster(id: $slug, idType: SLUG) {
    ...posterDetails
    date
    uri
    link
    featuredImage {
      node {
        id
        large: sourceUrl(size: LARGE)
        medium: sourceUrl(size: MEDIUM)
      }
    }
    relatedProducts: relatedProductsGroup {
      ...relatedProductsPosterGroup
    }
    PosterMetaGroup {
      date
      pdf {
        mediaItemUrl
      }
    }
    sources {
      edges {
        node {
          ...sourceDetails
        }
      }
    }
    subjects {
      edges {
        node {
          ...subjectDetails
        }
      }
    }
    seo {
      ...seo
    }
    relatedPosters(first: 10) {
      ...relatedPosters
    }
  }
}
