#import "./Fragments/PosterDetails.gql"
#import "./Fragments/SourceDetails.gql"
#import "./Fragments/SubjectDetails.gql"

query Poster($slug: ID!) {
  poster(id: $slug, idType: SLUG) {
    ...posterDetails
    date
    uri
    link
    featuredImage {
      node {
        id
        large: sourceUrl(size: LARGE)
        medium: sourceUrl(size: MEDIUM)
      }
    }
    PosterMetaGroup {
      date
      pdf {
        mediaItemUrl
      }
    }
    sources {
      edges {
        node {
          ...source
        }
      }
    }
    subjects {
      edges {
        node {
          ...subject
        }
      }
    }
  }
}
