#import "./Fragments/PosterDetails.gql"

query Posters(
  $first: Int
  $after: String
  $where: RootQueryToPosterConnectionWhereArgs
) {
  posters(first: $first, after: $after, where: $where) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        ...posterDetails
        uri
        featuredImage {
          node {
            id
            medium: sourceUrl(size: MEDIUM)
          }
        }
      }
    }
  }
}
