#import "./Fragments/Cart.gql"

mutation ADD_TO_CART($input: AddToCartInput!) {
  addToCart(input: $input) {
    cartItem {
      quantity
      subtotal
      subtotalTax
      tax
      total
    }
    cart {
      ...cart
    }
  }
}
