#import "./Fragments/Cart.gql"

mutation ADD_TO_CART(
  $productId: Int!
  $clientMutationId: String
  $quantity: Int
) {
  addToCart(
    input: {
      productId: $productId
      clientMutationId: $clientMutationId
      quantity: $quantity
    }
  ) {
    cart {
      ...cart
    }
  }
}
