mutation CHECKOUT(
  $billing: CustomerAddressInput
  $shipping: CustomerAddressInput
  $paymentMethod: String
  $clientMutationId: String
  $shipToDifferentAddress: Boolean
) {
  checkout(
    input: {
      paymentMethod: $paymentMethod
      billing: $billing
      shipping: $shipping
      clientMutationId: $clientMutationId
      shipToDifferentAddress: $shipToDifferentAddress
    }
  ) {
    clientMutationId
    redirect
    order {
      id
    }
    result
  }
}
